import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Line, Doughnut } from "react-chartjs-2"
import { Chart } from 'chart.js/auto'
import { useEffect, useState } from "react"

export default function Home() {
  const [homePrice, setHomePrice] = useState(425000);
  const [downPrice, setDownPrice] = useState(85000);
  const [year, setYear] = useState(30);
  const [rate, setRate] = useState(5);
  const [percent, setPercent] = useState(20);
  const [principal, setPrincipal] = useState(0);
  const [tax, setTax] = useState(280);
  const [total, setTotal] = useState(0);
  const [insurance, setInsurance] = useState(66);
  const [pmi, setPMI] = useState(0);
  const [foa, setFOA] = useState(0);
  const [ddata, setDData] = useState([]);
  const [ldata, setLData] = useState([]);
  const handleChange = async (e) => {
    let locVal = parseFloat(e.target.value);
    if(e.target.name === "homePrice"){
      setHomePrice(locVal)
      setDownPrice(locVal / 5)
    }
    if(e.target.name === "downPrice"){
      setDownPrice(locVal)
    }    
    if(e.target.name === "rate"){
      setRate(locVal)
    }
    if(e.target.name === "year"){
      setYear(locVal)
    }
    if(e.target.name === "tax"){
      setTax(locVal)
    }
    if(e.target.name === "foa"){
      setFOA(locVal)
    }
    if(e.target.name === "pmi"){
      setPMI(locVal)
    }
    if(e.target.name === "interest"){
      setInterest(locVal)
    }
    if(e.target.name === "insurance"){
      setInsurance(locVal)
    }
  }

  useEffect(() => {    
    setTotal(principal + foa + pmi + tax + insurance);
    setDData([principal, tax, insurance, pmi, foa]);
  }, [foa, pmi, principal, tax, insurance])

  useEffect(() => {    
    let P = homePrice - downPrice;
    let r = rate / 12 / 100;
    let n = year * 12;
    let M = P * r * Math.pow(1 + r, n) / (Math.pow(1 + r, n)- 1);
    setPrincipal(parseInt(M));
  }, [downPrice, homePrice, rate, year])

  useEffect(() => {
    setPercent((100 * downPrice / homePrice).toFixed(0));
  }, [downPrice, homePrice])

  const labels = [
    "Principal & Interest",
    "Property Tax",
    "Homeowner's insurance",
    "PMI",
    "HOA fees"
  ];
  const doughnutdata = {
    labels: labels,
    datasets: [
      {
        label: "Monthly payment breakdown",
        data: ddata,
        backgroundColor: [
          "#4949d0",
          "#66ff99",
          "#4d94ff",
          "#ff66ff",
          "#5cd65c",
        ],
        borderColor: [
          "#008800",
          "#008800",
          "#880000",
          "#008800",
          "#008888",
          "#FF0000",
        ],
        borderWidth: 0,
        hoverBorderWidth: 0,
        hoverBorderColor: [
          "rgb(255, 99, 132)",
          "#006600",
          "#880000",
          "#008800",
          "#008888",
          "#FF0000",
        ],
      },
    ],
  };
  
  const linedata = {
    type: "spline",
    labels: ["2023", "2033", "2043", "2053"],
    datasets: [
      {
        label: "Principal & interest",
        data: [1033, 953, 685, 140],
        fill: false,
        backgroundColor: "#4949d0",
        borderColor: "rgba(75,192,192,1)"
      },
      {
        label: "Property tax",
        data: [33, 625, 935, 1051],
        fill: false,
        borderColor: "#66ff99"
      },
      {
        label: "Principal & interest",
        data: [10, 225, 535, 1151],
        fill: false,
        borderColor: "#742774"
      }
    ]
  };
  
  return (
    <>
      <Head>
        <title>Mortgage Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"container " + styles.main}>
        <div className={styles.header}>
          <h1>Mortgage Calculator</h1>
        </div>
        <div className='row'>
          <div className='col-md-4'>
            <p className={styles.label}>Home Price($)</p>
            <input type={`number`} min={0} placeholder={`425000`} value={homePrice} className={`form-control ` + styles.dollar} onChange={handleChange} name="homePrice" />
            <p className={styles.label}>Down Payment($ / {percent}%)</p>
            <input type={`number`} min={0} placeholder={`8500`} className={`form-control`} value={downPrice} onChange={handleChange} name="downPrice" />
            <p className={styles.label}>Loan Term</p>
            <select className={`form-control`} defaultValue={year} name="year" onChange={handleChange}>
              <option value={5}>5 Years</option>
              <option value={10}>10 Years</option>
              <option value={15}>15 Years</option>
              <option value={20}>20 Years</option>
              <option value={25}>25 Years</option>
              <option value={30}>30 Years</option>
            </select>
            <p className={styles.label}>Interest Rate(%)</p>
            <input type={`number`} min={0} placeholder={`5`} max={100} className={`form-control`} value={rate} name="rate" onChange={handleChange} />
            <p className={styles.label}>Zip Code</p>
            <input type={`number`} min={0} placeholder={`680000`} className={`form-control`} />
            <p className={styles.tab}>Amortization</p>
            <Line 
              data={linedata}
              options={{
                plugins: {
                  legend: {
                    display: false,
                    labels: {
                      padding: 20
                    },
                  },
                }}
              } 
              redraw={true} 
            />
            <br />
            <table className='table'>
              <tbody>
                <tr>
                  <td></td>
                  <td className={styles.rightText}>
                    <p>As of April 2026</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p className={styles.label}>Principal paid</p>
                  </td>
                  <td className={styles.rightText}>
                    <p className={styles.label}>$16,298</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p className={styles.label}>Interest paid</p>
                  </td>
                  <td className={styles.rightText}>
                    <p className={styles.label}>$51,227</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p className={styles.label}>Loan balance</p>
                  </td>
                  <td className={styles.rightText}>
                    <p className={styles.label}>$323,702</p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className='col-md-8'>
            <p className={styles.tab}>Payment Breakdown</p>
            <h2>Monthly Payment Breakdown</h2>
            <div className={`row`}>
              <div className={'col-md-6 text-center '+styles.relativeDiv}>
                <br />
              <Doughnut
                data={doughnutdata}
                options={{
                  maintainAspectRatio: true,
                  plugins: {
                    legend: {
                      display: false,
                      labels: {
                        padding: 20
                      },
                    },
                  },
                }}
              />
              <span className={styles.totalFee}>${total}</span>
              </div>
              <div className='col-md-6'>
                <table className='table'>
                  <tbody>
                    <tr>
                      <td>
                        <p className={styles.label}><span className={styles.circlePrincipalMark}></span>Principal & interest</p>
                      </td>
                      <td width={20}></td>
                      <td className={styles.secondColumn}>
                        <p className={styles.boldText}>${principal}</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <p className={styles.label}><span className={styles.circleTaxMark}></span>Property tax</p>
                      </td>
                      <td width={20}><span className={styles.Operator}>+</span></td>
                      <td>
                        <input type={`number`} min={0} placeholder={0.00} className={`form-control`} name="tax" value={tax} onChange={handleChange} />
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <p className={styles.label}><span className={styles.circleInsuranceMark}></span>Homeowner&#39;s insurance</p>
                      </td>
                      <td width={20}><span className={styles.Operator}>+</span></td>
                      <td>
                        <input type={`number`} min={0} placeholder={0.00} className={`form-control`} name="insurance" value={insurance} onChange={handleChange} />
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <p className={styles.label}><span className={styles.circlePMIMark}></span>PMI</p>
                      </td>
                      <td width={20}><span className={styles.Operator}>+</span></td>
                      <td>
                        <input type={`number`} min={0} placeholder={0.00} className={`form-control`} name="pmi" value={pmi} onChange={handleChange} />
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <p className={styles.label}><span className={styles.circleHOAMark}></span>HOA fees</p>
                      </td>
                      <td width={20}><span className={styles.Operator}>+</span></td>
                      <td>
                        <input type={`number`} min={0} placeholder={0.00} className={`form-control`} name="foa" value={foa} onChange={handleChange} />
                      </td>
                    </tr>
                  </tbody>
                </table>
                <div className='row'>
                  <div className='col-md-8'>
                    <p className={styles.boldText}>Total monthly payment</p>
                  </div>
                  <div className={'col-md-4 ' + styles.rightText}>
                    <p className={styles.boldText}>${total}</p>
                  </div>
                </div>
              </div>
            </div>
            <br /><br />
            <h2>Current Mortgage Rates for March 12, 2023</h2>
            <div className='row'>
              <div className='col-md-12'>
                <hr />
                <table className='table'>
                  <tbody>
                    <tr>
                      <td>Lender</td>
                      <td>APR</td>
                      <td>Rate</td>
                      <td>Mo.Payment</td>
                      <td>Sort By</td>
                    </tr>
                    <tr>
                      <td>
                        <h1 className={styles.boldText}>Sage</h1>
                        <p className={styles.detailInfo}>30 year Fixed</p>
                      </td>
                      <td>
                        <span className={styles.percentBadge}>7.00%</span>
                        <p className={styles.detailInfo}>Mar 12, 2023</p>
                      </td>
                      <td>                        
                        <span className={styles.percentBadge}>7.00%</span>
                        <p className={styles.detailInfo}>Points 0</p>
                      </td>
                      <td>                        
                        <span className={styles.percentBadge}>$4,631</span>
                        <p className={styles.detailInfo}>Fees $0</p>
                      </td>
                      <td className={styles.verticalAlign}>
                        <button className={'btn ' + styles.btnNext}>Next &#8594;</button>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <h3 className={styles.weslend}><span className={styles.wesText}>Wes</span><span className={styles.lendText}>Lend</span></h3>
                        <p className={styles.detailInfo + ' text-justify'}>FINANCIAL</p>
                        <p className={styles.detailInfo}>30 year Fixed</p>
                      </td>
                      <td>
                        <span className={styles.percentBadge}>6.51%</span>
                        <p className={styles.detailInfo}>Mar 12, 2023</p>
                      </td>
                      <td>                        
                        <span className={styles.percentBadge}>6.38%</span>
                        <p className={styles.detailInfo}>Points 1125</p>
                      </td>
                      <td>                        
                        <span className={styles.percentBadge}>$4,342</span>
                        <p className={styles.detailInfo}>Fees $9,385</p>
                      </td>
                      <td className={styles.verticalAlign}>
                        <button className={'btn ' + styles.btnNext}>Next &#8594;</button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <hr />
        <div className='row'>
          <div className={'col-md-4 ' + styles.rightBorderBox}>
            <h3 className={styles.boldText}>Are you a first time home buyer?</h3>
            <button className={styles.btnYes}>Yes</button>
            <button className={styles.btnNo}>No</button>
          </div>
          <div className={'col-md-8'}>
            <div className='row'>
              <div className='col-md-1'></div>
              <div className={'col-md-2'}><h5 className={styles.dottedLabel}>Provincial</h5></div>
              <div className='col-md-7'><hr className={styles.dottedLine} /></div>
              <div className='col-md-2'><h5 className={styles.dottedLabel}>$2,000</h5></div>
            </div>
            <div className='row'>
              <div className='col-md-1'></div>
              <div className={'col-md-2'}><h5 className={styles.dottedLabel}>Municipal</h5></div>
              <div className='col-md-7'><hr className={styles.dottedLine} /></div>
              <div className='col-md-2'><h5 className={styles.dottedLabel}>$2,000</h5></div>
            </div>
            <div className='row'>
              <div className='col-md-1'></div>
              <div className={'col-md-2'}><h5 className={styles.dottedLabel}>Rebate</h5></div>
              <div className='col-md-7'><hr className={styles.dottedLine} /></div>
              <div className='col-md-2'><h5 className={styles.dottedLabel}>$2,000</h5></div>
            </div>
            <div className='row'>
              <div className={'col-md-3'}><h5 className={styles.dottedLabel +" "+ styles.boldText}>Land transfer tax</h5></div>
              <div className='col-md-7'><hr className={styles.dottedLine} /></div>
              <div className='col-md-2'><h5 className={styles.dottedLabel}>$2,000</h5></div>
            </div>
          </div>
        </div>
        <div className='row'>
          <div className={'col-md-12 card ' + styles.card}>
            <p>Cash needed to close</p>
          </div>
        </div>
        <div className='row'>
          <div className={'col-md-12 card ' + styles.card}>
            <p>Monthly experiences</p>
          </div>
        </div>
      </main>
      <br />
      <br />
      <br />
      <p className='text-center'>Mortgage Calculator @ 2023</p>
      <br />
    </>
  )
}
